spring:
  security:
    oauth2:
      authoriationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              client-id: "crm"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              authorization-grant-type: "authorization_code,refresh_token,client_credentials"
              redirect-uri: "http://127.0.0.1:8082/login/oauth2/code/spring"
              scopes: "user.read, user.write, openid"
              client-authentication-method: "client_secret_basic"
